docs_list_title: Products
docs:

- title: Wireless Motion-Sensing Lighting Control
  price: $29.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-motion-sensing-lighting-control
  image_path: ./img/products/36235.png
  addcart_link: https://byjasco.com/products/1312/add-to-cart
  category: kit
  rating: 10
  
- title: Wireless Door Sensor Lighting Control
  price: $24.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-door-sensor-lighting-control
  image_path: ./img/products/36236.png
  addcart_link: https://byjasco.com/products/1313/add-to-cart
  category: kit 
  rating: 10

- title: Wireless Remote w/ Countdown Timer Lighting Control
  price: $24.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-remote-countdown-timer-lighting-control
  image_path: ./img/products/36240.png
  addcart_link: https://byjasco.com/products/1315/add-to-cart
  category: kit
  rating: 10

- title: Wireless Remote with Dimming Lighting Control
  price: $29.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-remote-dimming-lighting-control
  image_path: ./img/products/37781.png
  addcart_link: https://byjasco.com/products/1317/add-to-cart
  category: kit
  rating: 10

- title: Wireless Dusk-to-Dawn Sensor Lighting Control
  price: $24.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-dusk-dawn-sensor-lighting-control
  image_path: ./img/products/36237.png
  addcart_link: https://byjasco.com/products/1314/add-to-cart
  category: kit
  rating: 10
  
- title: Wireless Remote Lighting Control
  price: $19.99
  jasco_link: https://byjasco.com/products/myselectsmart-wireless-remote-lighting-control
  image_path: ./img/products/36523.png
  addcart_link: https://byjasco.com/products/1316/add-to-cart
  category: kit
  rating: 10
  
